version: "3.8"
services:
  # Django application server
  server:
    build: .
    ports:
      - "8000:8000"  # Expose the Django app on port 8000
    depends_on:
      - db  # Ensure the database starts before the Django server
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    volumes:
      - .:/backend  # Mount the project directory to /backend inside the container

  # PostgreSQL database service
  db:
    image: postgres:13  # Use PostgreSQL 13 image
    restart: always
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: database1
      POSTGRES_PASSWORD: database1
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist database data
    expose:
      - 5432  # Expose the PostgreSQL port for internal communication

# Define a named volume to persist database data
volumes:
  db-data:
