version: '3'

services:
  client:
    build: client
    container_name: client
    ports:
      - '8081:8080'  # Updated port mapping
    networks:
      - app-network

  server:
    build: server
    container_name: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8081  # Updated to match new client port
      - JWT_SECRET=update_your_JWT_secret
      - MONGO_URI=mongodb://mongo:27017/mern_ecommerce
    ports:
      - '3000:3000'
    command: [
        'sh',
        '-c',
        'npm run seed:db admin@example.com admin123 && npm start'
      ]
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
